### ISSUE TITLE
race condition when docker process is closing and trying to forward data from stdin

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-cluster#49]
This is a pretty minor bug, but is confusing, so we should fix.  I noticed when I hit enter a bunch of times while terraform was ending.  If the timing works that the process has closed, but the PipedOutputStream pipe has not, you can get this exception:

```Exception in thread "Thread-1" java.io.IOException: Pipe closed
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
	at java.io.PipedInputStream.receive(PipedInputStream.java:226)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at java.io.OutputStream.write(OutputStream.java:75)
	at com.thelastpickle.tlpcluster.Docker$runContainer$redirectStdInputThread$1.invoke(Docker.kt:192)
	at com.thelastpickle.tlpcluster.Docker$runContainer$redirectStdInputThread$1.invoke(Docker.kt:24)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)```

**Comment by ossarga** [comment]
Idea would be to capture the exception and swallow it.
